/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.GUI.load;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import UserInterface.GUI.views.Books;
import UserInterface.GUI.views.Principal;
import UserInterface.GUI.views.Reportes;
import UserInterface.GUI.views.Returns;
import UserInterface.GUI.views.Usuarios;
import UserInterface.GUI.views.lending;

/**
 *
 * @author Suco
 */
public class Dashboard extends javax.swing.JFrame {
    int xmouse, ymouse;
    public Dashboard() {
        
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setImagen(image, "C:\\Users\\Suco\\Pictures\\img\\logo.jpg");
        setImagen(dev, "C:\\Users\\Suco\\Pictures\\img\\dev.jpg");
        setImagen(ho, "C:\\Users\\Suco\\Pictures\\img\\home.jpg");
        setImagen(usua, "C:\\Users\\Suco\\Pictures\\img\\usua.jpg");
        setImagen(repo, "C:\\Users\\Suco\\Pictures\\img\\fac.jpg");
        setImagen(lib, "C:\\Users\\Suco\\Pictures\\img\\libro.jpg");
        setImagen(pres3, "C:\\Users\\Suco\\Pictures\\img\\presta.jpg");
        dt();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcentral = new javax.swing.JPanel();
        panelbarra = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonhome = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        dev = new javax.swing.JLabel();
        ho = new javax.swing.JLabel();
        usua = new javax.swing.JLabel();
        repo = new javax.swing.JLabel();
        lib = new javax.swing.JLabel();
        pres3 = new javax.swing.JLabel();
        barahori = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombrelib = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelcentral.setBackground(new java.awt.Color(255, 255, 255));
        panelcentral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelcentralMouseDragged(evt);
            }
        });
        panelcentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelcentralMousePressed(evt);
            }
        });
        panelcentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbarra.setBackground(new java.awt.Color(204, 153, 0));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        image.setText("jLabel1");

        botonhome.setBackground(new java.awt.Color(153, 102, 0));
        botonhome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonhome.setForeground(new java.awt.Color(255, 255, 255));
        botonhome.setText("Home");
        botonhome.setBorder(null);
        botonhome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhomeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Devoluciones");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Usuarios");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 102, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Libros");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 102, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Prestamos");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setBackground(new java.awt.Color(153, 102, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Reportes");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dev.jpg"))); // NOI18N
        dev.setText("jLabel3");
        dev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                devMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                devMouseExited(evt);
            }
        });

        ho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.jpg"))); // NOI18N
        ho.setText("jLabel3");
        ho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoMouseExited(evt);
            }
        });

        usua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usua.jpg"))); // NOI18N
        usua.setText("jLabel3");
        usua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuaMouseExited(evt);
            }
        });

        repo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fac.jpg"))); // NOI18N
        repo.setText("jLabel3");
        repo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        repo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                repoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                repoMouseExited(evt);
            }
        });

        lib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/libro.jpg"))); // NOI18N
        lib.setText("jLabel3");
        lib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                libMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                libMouseExited(evt);
            }
        });

        pres3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/presta.jpg"))); // NOI18N
        pres3.setText("jLabel3");
        pres3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pres3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pres3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pres3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelbarraLayout = new javax.swing.GroupLayout(panelbarra);
        panelbarra.setLayout(panelbarraLayout);
        panelbarraLayout.setHorizontalGroup(
            panelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbarraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lib, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(usua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(dev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pres3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(repo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelbarraLayout.setVerticalGroup(
            panelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbarraLayout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbarraLayout.createSequentialGroup()
                        .addComponent(botonhome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbarraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelbarraLayout.createSequentialGroup()
                        .addComponent(ho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pres3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dev, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lib, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(repo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        panelcentral.add(panelbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 590));

        barahori.setBackground(new java.awt.Color(204, 153, 0));

        fecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fecha.setText("Hoy es (dayname) (day) de (month) de (year) ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Biblioteca/ Permisos / Disponibidad");

        javax.swing.GroupLayout barahoriLayout = new javax.swing.GroupLayout(barahori);
        barahori.setLayout(barahoriLayout);
        barahoriLayout.setHorizontalGroup(
            barahoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barahoriLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(barahoriLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        barahoriLayout.setVerticalGroup(
            barahoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barahoriLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fecha)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelcentral.add(barahori, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 760, 120));

        nombrelib.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nombrelib.setForeground(new java.awt.Color(153, 102, 0));
        nombrelib.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombrelib.setText("SUEÑOS EN PAPEL");
        panelcentral.add(nombrelib, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 290, 40));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        panelcentral.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 760, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelcentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelcentral, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseEntered
        panelbarra.setBackground(new java.awt.Color(102, 153, 255));
    }//GEN-LAST:event_hoMouseEntered

    private void hoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoMouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_hoMouseExited

    private void pres3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pres3MouseEntered
        panelbarra.setBackground(new java.awt.Color(102, 153, 0));
    }//GEN-LAST:event_pres3MouseEntered

    private void pres3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pres3MouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_pres3MouseExited

    private void devMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devMouseEntered
        panelbarra.setBackground(new java.awt.Color(102, 153, 255));
    }//GEN-LAST:event_devMouseEntered

    private void devMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devMouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_devMouseExited

    private void usuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuaMouseEntered
        panelbarra.setBackground(new java.awt.Color(102, 153, 0));
    }//GEN-LAST:event_usuaMouseEntered

    private void usuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuaMouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_usuaMouseExited

    private void libMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libMouseEntered
        panelbarra.setBackground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_libMouseEntered

    private void libMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libMouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_libMouseExited

    private void repoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repoMouseEntered
        panelbarra.setBackground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_repoMouseEntered

    private void repoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repoMouseExited
        panelbarra.setBackground(new java.awt.Color(204, 153, 0));
    }//GEN-LAST:event_repoMouseExited

    private void panelcentralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcentralMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_panelcentralMousePressed

    private void panelcentralMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcentralMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this. setLocation(x- xmouse, y- ymouse);
    }//GEN-LAST:event_panelcentralMouseDragged

    private void botonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhomeActionPerformed
        ShowJPanel(new Principal());
    }//GEN-LAST:event_botonhomeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ShowJPanel(new lending());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ShowJPanel(new Returns());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ShowJPanel(new Books());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ShowJPanel(new Reportes());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         ShowJPanel(new Usuarios());
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    private void setImagen(JLabel img, String root) {
        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(icon);
        this.repaint();
    }
    public void dt(){
        LocalDate now= LocalDate.now();
        Locale spanishLocale= new Locale("es", "ES");
        fecha.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMM MM 'de' yyyy", spanishLocale)));
    }
    private void InitContent(){
        ShowJPanel(new Returns());
    }
    private void ShowJPanel(JPanel pl){
        pl.setSize(760, 410);
        pl.setLocation(0, 0);
        content.removeAll();
        content.add(pl, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barahori;
    private javax.swing.JButton botonhome;
    private javax.swing.JPanel content;
    private javax.swing.JLabel dev;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel ho;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lib;
    private javax.swing.JLabel nombrelib;
    private javax.swing.JPanel panelbarra;
    private javax.swing.JPanel panelcentral;
    private javax.swing.JLabel pres3;
    private javax.swing.JLabel repo;
    private javax.swing.JLabel usua;
    // End of variables declaration//GEN-END:variables

}
