/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package load;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Suco
 */
public class logAdmin extends javax.swing.JFrame {
    int xmouse, ymouse;
    /**
     * Creates new form logAdmin
     */
    public logAdmin() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setImagen(fondolog, "C:\\Users\\Suco\\Pictures\\img\\biblio.jpg");
        setImagen(iccorr, "C:\\Users\\Suco\\Pictures\\img\\corr.jpg");
        setImagen(icusua, "C:\\Users\\Suco\\Pictures\\img\\usua.jpg");
        setImagen(ictel, "C:\\Users\\Suco\\Pictures\\img\\cel.jpg");
        setImagen(icpass, "C:\\Users\\Suco\\Pictures\\img\\cont.jpg");
        setImagen(icjor, "C:\\Users\\Suco\\Pictures\\img\\jor.jpg");
    }    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prin = new javax.swing.JPanel();
        fondolog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        textusua = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        usuario1 = new javax.swing.JLabel();
        textusua1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        usuario2 = new javax.swing.JLabel();
        usuario3 = new javax.swing.JLabel();
        textusua3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        usuario4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        icjor = new javax.swing.JLabel();
        icusua = new javax.swing.JLabel();
        iccorr = new javax.swing.JLabel();
        icpass = new javax.swing.JLabel();
        ictel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prin.setBackground(new java.awt.Color(255, 255, 255));
        prin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                prinMouseDragged(evt);
            }
        });
        prin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                prinMousePressed(evt);
            }
        });
        prin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondolog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/biblio.jpg"))); // NOI18N
        fondolog.setText("jLabel1");
        prin.add(fondolog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRARSE¡");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 200, 40));

        jButton1.setBackground(new java.awt.Color(153, 102, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        prin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 100, 30));

        jButton2.setBackground(new java.awt.Color(153, 102, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        prin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 110, 40));

        usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario.setText("Usuario");
        prin.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 80, 30));

        textusua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textusua.setForeground(new java.awt.Color(204, 204, 204));
        textusua.setText("Ingrese su usuario");
        textusua.setBorder(null);
        textusua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(textusua, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 290, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        prin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 290, 10));

        usuario1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario1.setText("Correo");
        prin.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 80, 30));

        textusua1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textusua1.setForeground(new java.awt.Color(204, 204, 204));
        textusua1.setText("Ingrese su correo");
        textusua1.setBorder(null);
        textusua1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(textusua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 290, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        prin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 290, 10));

        usuario2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario2.setText("Password");
        prin.add(usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 80, 30));

        usuario3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario3.setText("Jornada");
        prin.add(usuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 80, 30));

        textusua3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textusua3.setForeground(new java.awt.Color(204, 204, 204));
        textusua3.setText("Número celular");
        textusua3.setBorder(null);
        textusua3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(textusua3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 290, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        prin.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 290, 10));

        usuario4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usuario4.setText("Teléfono");
        prin.add(usuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 80, 30));

        jComboBox1.setBackground(new java.awt.Color(153, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutina", "Vespertina", "Nocturna" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 290, 30));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 290, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        prin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 290, 10));

        icjor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/jor.jpg"))); // NOI18N
        icjor.setText("jLabel2");
        icjor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icjor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icjorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icjorMouseExited(evt);
            }
        });
        prin.add(icjor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 60, 50));

        icusua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/usua.jpg"))); // NOI18N
        icusua.setText("jLabel2");
        icusua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icusua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icusuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icusuaMouseExited(evt);
            }
        });
        prin.add(icusua, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 60, 50));

        iccorr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/corr.jpg"))); // NOI18N
        iccorr.setText("jLabel2");
        iccorr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iccorr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iccorrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iccorrMouseExited(evt);
            }
        });
        prin.add(iccorr, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 60, 50));

        icpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cont.jpg"))); // NOI18N
        icpass.setText("jLabel2");
        icpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icpassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icpassMouseExited(evt);
            }
        });
        prin.add(icpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 60, 50));

        ictel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cel.jpg"))); // NOI18N
        ictel.setText("jLabel2");
        ictel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ictel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ictelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ictelMouseExited(evt);
            }
        });
        prin.add(ictel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 60, 50));

        jButton3.setBackground(new java.awt.Color(153, 102, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancelar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prin.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prin, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(prin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icusuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icusuaMouseEntered
        prin.setBackground(new java.awt.Color(153, 204, 255));
    }//GEN-LAST:event_icusuaMouseEntered

    private void icusuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icusuaMouseExited
        prin.setBackground(new java.awt.Color(150, 92, 0));
    }//GEN-LAST:event_icusuaMouseExited

    private void iccorrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iccorrMouseEntered
        prin.setBackground(new java.awt.Color(153, 153, 0));
    }//GEN-LAST:event_iccorrMouseEntered

    private void iccorrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iccorrMouseExited
        prin.setBackground(new java.awt.Color(153, 0, 0));
    }//GEN-LAST:event_iccorrMouseExited

    private void icpassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icpassMouseEntered
        prin.setBackground(new java.awt.Color(0, 153, 204));
    }//GEN-LAST:event_icpassMouseEntered

    private void icpassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icpassMouseExited
        prin.setBackground(new java.awt.Color(255, 204, 153));
    }//GEN-LAST:event_icpassMouseExited

    private void ictelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ictelMouseEntered
        prin.setBackground(new java.awt.Color(102, 153, 0));
    }//GEN-LAST:event_ictelMouseEntered

    private void ictelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ictelMouseExited
        prin.setBackground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_ictelMouseExited

    private void icjorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icjorMouseEntered
        prin.setBackground(new java.awt.Color(153, 204, 102));
    }//GEN-LAST:event_icjorMouseEntered

    private void icjorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icjorMouseExited
        prin.setBackground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_icjorMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        prin.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        prin.setBackground(new java.awt.Color(153, 153, 0));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        prin.setBackground(new java.awt.Color(0, 102, 153));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        prin.setBackground(new java.awt.Color(102, 153, 255));
    }//GEN-LAST:event_jButton1MouseExited

    private void prinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prinMousePressed
        xmouse= evt.getX();
        ymouse= evt.getY();
    }//GEN-LAST:event_prinMousePressed

    private void prinMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prinMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this. setLocation(x- xmouse, y- ymouse);
    }//GEN-LAST:event_prinMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FlatLightLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logAdmin().setVisible(true);
            }
        });
    }
    private void setImagen(JLabel img, String root) {
        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(imagen.getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(icon);
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondolog;
    private javax.swing.JLabel iccorr;
    private javax.swing.JLabel icjor;
    private javax.swing.JLabel icpass;
    private javax.swing.JLabel ictel;
    private javax.swing.JLabel icusua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel prin;
    private javax.swing.JTextField textusua;
    private javax.swing.JTextField textusua1;
    private javax.swing.JTextField textusua3;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    private javax.swing.JLabel usuario3;
    private javax.swing.JLabel usuario4;
    // End of variables declaration//GEN-END:variables

}
